#!/usr/bin/env bash
# manage_my_process script

case "$1" in
  "start")
    if [ -f /var/run/my_process.pid ]; then
      echo "manage_my_process is already running."
    else
      ./my_process.sh &
      echo "$!" > /var/run/my_process.pid
      echo "manage_my_process started."
    fi
    ;;
  "stop")
    if [ -f /var/run/my_process.pid ]; then
      pid=$(cat /var/run/my_process.pid)
      kill "$pid"
      rm -f /var/run/my_process.pid
      echo "manage_my_process stopped."
    else
      echo "manage_my_process is not running."
    fi
    ;;
  "restart")
    $0 stop
    $0 start
    echo "manage_my_process restarted."
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
    ;;
esac

