#!/usr/bin/env bash
# This Bash script stops the "7-highlander" process

pkill -f "7-highlander"
if [ $? -eq 0 ]; then
    echo "Successfully stopped '7-highlander' process."
else
    echo "Process '7-highlander' not found or could not be stopped."
fi

