#!/usr/bin/env bash
# This Bash script kills the process named "7-highlander."

pkill -f "7-highlander"

if [ $? -eq 0 ]; then
    echo "Successfully killed '7-highlander' process."
else
    echo "Process '7-highlander' not found or could not be killed."
fi

